version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:5000" # Expose Flask on port 8000
    environment:
      FLASK_ENV: ${FLASK_ENV}
      FLASK_APP: app.py
      DATABASE_URL: ${DATABASE_URL} # External Postgres connection string
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    restart: always
